### ISSUE TITLE
STA9750 thanhtdao922 MiniProject #01

### ISSUE THREAD

**Issue by thanhtdao922** [thanhtdao922/STA9750-2024-FALL#2]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #01 - check it out!

https://thanhtdao922.github.io/STA9750-2024-FALL/mp01.html

**Comment by michaelweylandt** [comment]
Thanks @thanhtdao922 !

Peer Feedback:

- @lavs10
- @SethKauf
- @CristelKZuniga
- @plnrbrt

It is now time for the peer feedback round for Mini-Project #01. Please
review @thanhtdao922's submission for this mini-project and provide peer feedback.

Using the rubric at https://michael-weylandt.com/STA9750/miniprojects/mini01.html#rubric,
please grade their submission out of a total of 50 points.

For each of the five categories, please give them a separate score and provide
a total (sum) score across the entire assignment. Feel free to assign extra
credit if you feel it is warranted (following the rubric).

If you give a score of less than 5 for any category, please provide a suggestion
for improvement. (You can also give suggestions for any element they did well -
more feedback is always great!)

As you go through this peer feedback exercise, think about what you particularly
like about this submission and how you can incorporate that approach in your future
work. If something is particularly insightful or creative, give some kudos!

Evaluators: This should take you around 15 minutes per peer feedback. You are
not required to engage in substantial back-and-forth with @thanhtdao922, but you are of course
welcome to initiate a discussion.

@thanhtdao922: please engage fully with your peers. They are here to help you!

Submission URL should be: https://thanhtdao922.github.io/STA9750-2024-FALL/mp01.html

Feel free to link to other repos, the course documentation, or other useful
examples.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by SethKauf** [comment]
Hey @thanhtdao922 ,

I just checked your .qmd file, I think you should really switch all of the instances where you have

`{r echo=FALSE, ...}`

to

`{r echo=TRUE ...}`

because as-of-now, none of the code is displaying at the top of the website, nor for several of the other tasks including the first two tasks and the Farebox Recovery Analysis.

Using the code from your .qmd file and what is displayed on the website, here's my grade for your project:

Written Communication: 7/10
The information that is on the displayed page is nice for the most part. The questions however are bunched up and it's difficult to immediately tell where a code blocks start and end (remember to add the `{r}` argument to any r code you push up in markdown) and when you've moved on to another question. I also think your decisions to emphasize parts sentences could be improved, ie bolding import numbers that answer questions. There was a mostly-good attempt to highlight key findings. I think using some kind of system to break up questions either bullet points or a "1. 2. 3." list-type system would have been very useful.

Project Skeleton: 9/10
I copied the code from your .qmd file and was able to run it through to answer the questions. Taking off a point because I had to go through the .qmd file.

Formatting & Display: 7/10
I'm not a huge fan of the code blocks and their outputs as-is. However, the tables that were in the code were displayed correctly and fine for the most part. I thought a lot more could have been done with the displays for the output tables from the further tasks and questions.

Code Quality: 4/10
I'm really sorry for this, but given the first two tasks don't even appear on the .html page, I can't really justify anything better. The code you did have on the page was fine and had good descriptive variable/table names, though it lacked any comments. You also re-import libraries a lot throughout the script  and have repetitive blocks, ie with Task 1, where you write

```{r echo=FALSE, message=FALSE}
## Task 1: Create Syntactic Names
USAGE <- rename(USAGE, "metro_area" = "UZA Name")
USAGE <- rename(USAGE, "unlinked_passenger_trips" = "UPT")
USAGE <- rename(USAGE, "vehicle_revenue_miles" = "VRM")
USAGE <- rename(USAGE, "NTD_ID" = "NTD ID")
```

You could have just done this in a single function:

```{r echo=TRUE, message=FALSE}
## Task 1: Create Syntactic Names
USAGE <- rename(USAGE, "metro_area" = "UZA Name",
                "unlinked_passenger_trips" = "UPT",
                "vehicle_revenue_miles" = "VRM",
                "NTD_ID" = "NTD ID")
```

That's not to say it's necessarily always bad to rename it one item at a time, but it's certainly a lot less efficient (and you can collapse the above code down to a single line if you really wanted to).

Data Preparation: 10/10
N/A

Overall: 37/50
There is a lot of potential here, and I would actually like to review this again with just the Markdown code re-formatted and the R code fully displayed if @michaelweylandt is okay with that.

**Comment by thanhtdao922** [comment]
@SethKauf thanks for the feedback!

**Written Communication:** I wanted the project to flow more like an actual report, rather than a "question and answer" project format, which is why I formatted it the way I did instead of with bullet points, but I definitely see where you're coming from. 

**Formatting and Display:** As the course goes on I'll update with some graphs or charts that would emphasize the data.

**Code Quality:** Personally it feels better for me to break it into multiple blocks, but it does get repetitive. I'll probably start out writing the code in multiple blocks, then break it into one single function after the fact to make the code cleaner. Thanks for the advice. As for the first two tasks (renaming UZA Name to metro_area / recoding the Mode column), I didn't explicitly show the code, but the results are displayed in the first table, with the UZA Name already being renamed and the Mode column displaying all the renamed phrases. 

Once @michaelweylandt finishes grading, I'll definitely update the project and implement your feedback. Thanks!

**Comment by charles-ramirez** [comment]
Hi @lavs10 @CristelKZuniga @plnrbrt, 

This is just a reminder that your peer review is due at 11:45 pm.

**Comment by lavs10** [comment]
Hi @thanhtdao922 ,

My feedback for Mini-Project 01 is below:

Written Content: 7/10 - The introduction is solid, but there’s a lack of clarity in the motivation for each analysis step. Providing more context on why certain choices were made would improve the narrative.

Project Skeleton: 8/10 - Most tasks were well-executed, but the response for Task 3 was incomplete, as there was no explanation accompanying the output.

Formatting and Display: 6/10 - The tables were displayed correctly, but they lacked captions and clear headers, making it difficult to interpret the results. Adding headings and improving table readability would enhance the presentation.

Code Quality: 5/10 - The code ran successfully, but some variable names were unclear, and there were minimal comments to guide the reader through the logic. Enhancing code readability and providing more detailed comments would help.

Total Score: 36/50

Overall, the project has potential, but there are areas that need improvement in terms of communication and clarity.

**Comment by plnrbrt** [comment]
Hi @thanhtdao922!
Thank you very much for sharing your mini-project 1! Here are my comments below:
Written Communication: 7/10
I like the fact that you gave an answer to every task but it is complicated to understand when you put the answer before the code that gets you to this conclusion. It would have also been nice to add in your introduction where the data came from by putting markdown hyperlinks linked to the data website. Also, give more context and description about the main table that you are displaying on top of your website page. Finally, it would have been nice that the code displayed the answer to better understand and for a better flow when reading.
Project Skeleton: 10/10 
Everything worked and all the tasks from the instructor have been answered.
Formatting and Display: 7/10
The two tables you put on your mini project are well formatted but I wish there were more descriptive tables. For example, you could have displayed some table by adding to your code a function to print out a table. I personally use the library(knitr). By calling the function "kable", this allows you to display your result in a table. 
Code Quality: 4/10
The code looks good but it's lacking of basic comments so it is hard to understand its purpose and what do we want to get out of this code.
Data Preparation: 10/10
Total: 38/50

**Comment by thanhtdao922** [comment]
Hello all,
Thank you for your comments. After reviewing everything, I edited my project to reflect some of your feedback.

**Comment by CristelKZuniga** [comment]
Hello @thanhtdao922 

I didn’t see your project before the previous improvements were made, but from what I see now, it looks pretty good to me. Here are some comments:

- Written Communication (9):
The introduction and answers are clear, comprehensive, and well-structured.

- Project Skeleton (10):
All tasks are completed and functioning properly.

- Formatting & Display (9):
I like the colors used in your project. One distinctive aspect is how you utilized bold text; it provides a nice and comprehensive view for the reader.

- Code Quality (9):
The code appears to be functioning properly. I suggest adding some comments to explain the code for readers who may not be familiar with the subject.

- Data Preparation (10):

Thank you,
